version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ariadna-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ariadna
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: ariadna-backend
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/ariadna
    depends_on:
      - mongodb

volumes:
  mongodb_data:
